#!/usr/bin/env bash
# Sets up an nginx server

# Install nginx
apt-get update
apt-get -y install nginx

# Configure nginx to serve custom html content
echo "Hello World!" > /var/www/html/nginx-debian.html

# configure nginx to listen on port 80
sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-available/default

# Start nginx
service nginx restart