#!/usr/bin/env bash
# Script that fixes an nginx server to serve content from port 80
apt-get update -y
apt-get install nginx -y
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
