#!/usr/bin/env bash
# Displays "To inifinity and beyond" infinitely, delayed by 2s and is invincible to SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
