#!/usr/bin/env bash
# A script that loops from 1 to 10 with some good and bad luck

count=1
while [ $count -le 10 ]
do
    if [ $count == 4 ]
    then
        echo "bad luck"
    elif [ $count == 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    count=$(( count += 1 ))
done
