#!/usr/bin/env bash
# ascript that gives you information about the "school" file

school_path="school"

if [ -a "$school_path" ]; then
    echo "school file exists"
    if [ -s "$school_path" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$school_path" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
